### ISSUE TITLE
Merging Radical.Windows.Presentation.Puzzle into Radical.Windows.Presentation

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#12]
Related to #6 what about merging the "Radical.Windows.Presentation.Puzzle" projects for Universal Apps into the "Radical.Windows.Presentation", in the end we are shipping the PuzzleContainer in any case and adding to the Radical.Windows.Presentation project 5 more classes should not be a problem at all compared to one less dependency to download from Nuget.

@enosrecanati @micdenny comments?

**Comment by micdenny** [comment]
I think is a good idea, it's a kind of custom tiny IoC container, and should be hided, if someone want it to use in its project, it could simply copy the 5 classes instead of having a nuget package, I saw other projects do [this](https://github.com/mikehadlow/EasyNetQ/blob/master/Source/EasyNetQ/DefaultServiceProvider.cs).

**Comment by mauroservienti** [comment]
Migrated to: https://github.com/RadicalFx/radical-universal/issues/10
