### ISSUE TITLE
Support only .NET 4.5.2 and up

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#66]
Drop 3.5 and 4.0 support

**Comment by mauroservienti** [comment]
@micdenny thoughts?

**Comment by nazarenomanco** [comment]
Do you have idea of the solutions that are using the <= Fx4.0?

**Comment by mauroservienti** [comment]
that's the hard question @nazarenomanco. I hope that 3.5 is dead. 4.0 is the problem 😄

**Comment by micdenny** [comment]
I would avoid compile to 4.5.2, but 4.5, because pushing the user to build against 4.5.2 it's not a good idea IMHO, this is a framework and should be open to be used in many platform and compiler as possible, 3.5 actually is not dead, it is bounded with the operating system, so it will be supported until windows 10 will die, unfortunately I'm not joking (https://support.microsoft.com/en-us/gp/framework_faq/en-us):

>.NET Framework 3.5 SP1: Beginning with .NET Framework 3.5 Service Pack 1 (SP1) the .NET Framework is defined as a component instead of an independent product. So, support for .NET Framework 3.5 SP1 is driven by the support lifecycle policy of the Windows operating system (i.e. when Windows is in the Mainstream Support phase or Extended Support phase, so are its components). When a product such as Windows reaches the end of support, so do its related components. .NET Framework 3.5 SP1 is supported on Windows Server 2003 SP2, Windows Vista SP2, Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, Windows 8.1 Update, Windows Server 2012, Windows Server 2012 R2, and Windows 10 according to the end of support date for each operating system.

**BTW I think we could abandon at least the 3.5**, _but if we don't abandon also the 4.0 I don't see such an improvement to our ALM._

Abandon 4.0 I think would mean that we have to increase the major version all the Radical framework, push all the v1 TAGs in all the repo, and then that version will be compatible for >=3.5, so the community can easily fork and fix some big bad bug (BBB, I think I invented a new acronym or does it already exist? 😄) on their own.

what do think guys?

**Comment by mauroservienti** [comment]
Agree 😭 
Or we're able to drop both 3.5 and 4.0 or the benefit is near to zero. Let's keep this in the backlog and revisit later.

**Comment by mauroservienti** [comment]
replaced by #72
